#!/bin/bash

#AUZIO by Kamal Hakim
#finds songs based on a artist - song query and downloads and converts it
#kamal.hakim 05-28-16

song="$1"
dfreq="44100"
freq="${2:=$dfreq}"
cat logo

if [[ -z "${song}" ]]
then
	echo "to run enter: ./auzio Song"
	exit 0
else
	#check_tools
	song=${song// /+}
	song="${song}"
        title=$(echo "$1@$2" | tr '[a-z]' '[A-Z]')
	title=${title/+/-}
        echo -n "Finding: ${title}"
        echo "... "
	youtube-dl --extract-audio -o ${song}.mp3 "ytsearch:${song}+official+lyrics"
	ffmpeg -i ${song}.* -vn -acodec libmp3lame -ac 2 -qscale:a 4 -ar ${freq} "auzio-${title}.mp3"
	wait $!
	mv "auzio-${title}.mp3" /var/www/html/auzio/
	if [ -f ${song}.opus ]
        then
	rm ${song}.opus
	fi
	if [ -f ${song}.mp4 ]
        then
        rm ${song}.mp4
        fi
fi

exit 0
