#!/bin/bash

#AUZIO by Kamal Hakim
#finds songs based on a artist - song query and downloads and converts it
#kamal.hakim 05-28-16

song="$*"
cat logo
play_song()
{
	echo "Press enter to play!"
	read playnow
	mpg123 "$1" &> /dev/null &
        procid=$!
        echo "Now playing: $1"
        echo ""
	echo "Press enter to stop playing."
        read stopnow
        kill -9 $procid &> /dev/null &
	exit 0
}

check_tools()
{
	brew="$(which brew)"
        if [ -z $brew ]
        then
                echo "Installing Homebrew..."
                /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
                wait $!
        fi
	ytdl="$(which youtube-dl)"
        if [ -z $ytdl ]
        then
                echo "Installing YTDL..."
                brew install youtube-dl
                wait $!
        fi
        mpg="$(which mpg123)"
	if [ -z $mpg ]
        then
                echo "Installing MPG123..."
                brew install mpg123
                wait $!
        fi
	ffmpeg="$(which ffmpeg)"
        if [ -z $ffmpeg ]
        then
                echo "Installing FFMPEG..."
                brew install ffmpeg
                wait $!
        fi
}

re="^.* - .*$"
if [[ -z "${song}" ||! "$song" =~ $re ]]
then
	echo "to run enter: ./auzio Artist - Song"
	exit 0
else
	check_tools
	song=${song// /+}
	song="${song}"
        title=$(echo "$*" | tr '[a-z]' '[A-Z]')
	title=${title/+/-}
        echo -n "Finding: ${title}"
        echo "... "
	youtube-dl --extract-audio -o ${song}.mp3 "ytsearch:${song}+official+lyrics"
	ffmpeg -i ${song}.* -vn -acodec libmp3lame -ac 2 -qscale:a 4 -ar 48000 "Auzio-${title}.mp3"
	wait $!
	if [ -f ${song}.opus ]
        then
	rm ${song}.opus
	fi
	if [ -f ${song}.mp4 ]
        then
        rm ${song}.mp4
        fi
	play_song "Auzio-${title}.mp3"
fi

exit 0
